export enum JobsType {
  Archer = "Archer",
  Hunter = "Hunter",
  Ranger = "Ranger",
  Bowmaster = "Bowmaster",
  Crossbowman = "Crossbowman",
  Sniper = "Sniper",
  Marksman = "Marksman",
  Magician = "Magician",
  FirePoisonWizard = "Fire/Poison Wizard",
  IceLightningWizard = "Ice/Lightning Wizard",
  Cleric = "Cleric",
  FirePoisonMage = "Fire/Poison Mage",
  IceLightningMage = "Ice/Lightning Mage",
  Priest = "Priest",
  FirePoisonArchMage = "Fire/Poison Arch Mage",
  IceLightningArchMage = "Ice/Lightning Arch Mage",
  Bishop = "Bishop",
  Rogue = "Rogue",
  Brawler = "Brawler",
  Gunslinger = "Gunslinger",
  Marauder = "Marauder",
  Outlaw = "Outlaw",
  Buccaneer = "Buccaneer",
  Corsair = "Corsair",
  Thief = "Thief",
  Assassin = "Assassin",
  Bandit = "Bandit",
  Hermit = "Hermit",
  ChiefBandit = "Chief Bandit",
  NightLord = "Night Lord",
  Shadower = "Shadower",
  Swordman = "Swordman",
  Fighter = "Fighter",
  Page = "Page",
  Spearman = "Spearman",
  Crusader = "Crusader",
  WhiteKnight = "White Knight",
  DragonKnight = "Dragon Knight",
  Hero = "Hero",
  Paladin = "Paladin",
  DarkKnight = "Dark Knight",

  Begginer = "Begginer",
}

export const JobsMainType: any = {
  [JobsType.Archer]: JobsType.Archer,
  [JobsType.Magician]: JobsType.Magician,
  // [JobsType.Pirate]: JobsType.Pirate,
  [JobsType.Thief]: JobsType.Thief,
  // [JobsType.Warrior]: JobsType.Warrior,
  [JobsType.Begginer]: JobsType.Begginer,
};

export const JobsOrder = {
  [JobsType.Archer]: {
    firstJob: JobsType.Archer,
    secondJobs: [JobsType.Hunter, JobsType.Crossbowman],
    thirdJobs: [JobsType.Ranger, JobsType.Sniper],
    fourthJobs: [JobsType.Bowmaster, JobsType.Marksman],
  },
  [JobsType.Magician]: {
    firstJob: JobsType.Magician,
    secondJobs: [
      JobsType.FirePoisonWizard,
      JobsType.IceLightningWizard,
      JobsType.Cleric,
    ],
    thirdJobs: [
      JobsType.FirePoisonMage,
      JobsType.IceLightningMage,
      JobsType.Priest,
    ],
    fourthJobs: [
      JobsType.FirePoisonArchMage,
      JobsType.IceLightningArchMage,
      JobsType.Bishop,
    ],
  },
  // [JobsType.Pirate]: {
  //   firstJob: JobsType.Rogue,
  //   secondJobs: [JobsType.Brawler, JobsType.Gunslinger],
  //   thirdJobs: [JobsType.Marauder, JobsType.Outlaw],
  //   fourthJobs: [JobsType.Buccaneer, JobsType.Corsair],
  // },
  [JobsType.Thief]: {
    firstJob: JobsType.Thief,
    secondJobs: [JobsType.Assassin, JobsType.Bandit],
    thirdJobs: [JobsType.Hermit, JobsType.ChiefBandit],
    fourthJobs: [JobsType.NightLord, JobsType.Shadower],
  },
  // [JobsType.Warrior]: {
  //   firstJob: JobsType.Swordman,
  //   secondJobs: [JobsType.Fighter, JobsType.Page, JobsType.Spearman],
  //   thirdJobs: [JobsType.Crusader, JobsType.WhiteKnight, JobsType.DragonKnight],
  //   fourthJobs: [JobsType.Hero, JobsType.Paladin, JobsType.DarkKnight],
  // },
};
