const JOB_ID_NAMES: Record<number, string> = {
  0: 'Beginner',
  100: 'Warrior',   110: 'Fighter',      111: 'Crusader',        112: 'Hero',
  120: 'Page',      121: 'White Knight',  122: 'Paladin',
  130: 'Spearman',  131: 'Dragon Knight', 132: 'Dark Knight',
  200: 'Magician',
  210: 'F/P Wizard',    211: 'F/P Mage',     212: 'F/P Arch Mage',
  220: 'I/L Wizard',    221: 'I/L Mage',     222: 'I/L Arch Mage',
  230: 'Cleric',        231: 'Priest',        232: 'Bishop',
  300: 'Archer',    310: 'Hunter',        311: 'Ranger',          312: 'Bowmaster',
  320: 'Crossbowman',   321: 'Sniper',        322: 'Marksman',
  400: 'Rogue',     410: 'Assassin',      411: 'Hermit',          412: 'Night Lord',
  420: 'Bandit',    421: 'Chief Bandit',  422: 'Shadower',
  500: 'Pirate',    510: 'Brawler',       511: 'Marauder',        512: 'Buccaneer',
  520: 'Gunslinger',    521: 'Outlaw',        522: 'Corsair',
  1000: 'Noblesse',
  1100: 'Dawn Warrior',  1110: 'Dawn Warrior',  1111: 'Dawn Warrior',  1112: 'Dawn Warrior',
  1200: 'Blaze Wizard',  1210: 'Blaze Wizard',  1211: 'Blaze Wizard',  1212: 'Blaze Wizard',
  1300: 'Wind Archer',   1310: 'Wind Archer',   1311: 'Wind Archer',   1312: 'Wind Archer',
  1400: 'Night Walker',  1410: 'Night Walker',  1411: 'Night Walker',  1412: 'Night Walker',
  1500: 'Thunder Breaker', 1510: 'Thunder Breaker', 1511: 'Thunder Breaker', 1512: 'Thunder Breaker',
  2000: 'Legend',   2100: 'Aran',         2110: 'Aran',           2111: 'Aran',          2112: 'Aran',
};

export function getJobName(id: number): string {
  return JOB_ID_NAMES[id] ?? `Job ${id}`;
}

export enum JobsType {
  Archer = "Archer",
  Hunter = "Hunter",
  Ranger = "Ranger",
  Bowmaster = "Bowmaster",
  Crossbowman = "Crossbowman",
  Sniper = "Sniper",
  Marksman = "Marksman",
  Magician = "Magician",
  FirePoisonWizard = "Fire/Poison Wizard",
  IceLightningWizard = "Ice/Lightning Wizard",
  Cleric = "Cleric",
  FirePoisonMage = "Fire/Poison Mage",
  IceLightningMage = "Ice/Lightning Mage",
  Priest = "Priest",
  FirePoisonArchMage = "Fire/Poison Arch Mage",
  IceLightningArchMage = "Ice/Lightning Arch Mage",
  Bishop = "Bishop",
  Rogue = "Rogue",
  Brawler = "Brawler",
  Gunslinger = "Gunslinger",
  Marauder = "Marauder",
  Outlaw = "Outlaw",
  Buccaneer = "Buccaneer",
  Corsair = "Corsair",
  Thief = "Thief",
  Assassin = "Assassin",
  Bandit = "Bandit",
  Hermit = "Hermit",
  ChiefBandit = "Chief Bandit",
  NightLord = "Night Lord",
  Shadower = "Shadower",
  Swordman = "Swordman",
  Fighter = "Fighter",
  Page = "Page",
  Spearman = "Spearman",
  Crusader = "Crusader",
  WhiteKnight = "White Knight",
  DragonKnight = "Dragon Knight",
  Hero = "Hero",
  Paladin = "Paladin",
  DarkKnight = "Dark Knight",

  Begginer = "Begginer",
}

export const JobsMainType: any = {
  [JobsType.Archer]: JobsType.Archer,
  [JobsType.Magician]: JobsType.Magician,
  // [JobsType.Pirate]: JobsType.Pirate,
  [JobsType.Thief]: JobsType.Thief,
  // [JobsType.Warrior]: JobsType.Warrior,
  [JobsType.Begginer]: JobsType.Begginer,
};

export const JobsOrder = {
  [JobsType.Archer]: {
    firstJob: JobsType.Archer,
    secondJobs: [JobsType.Hunter, JobsType.Crossbowman],
    thirdJobs: [JobsType.Ranger, JobsType.Sniper],
    fourthJobs: [JobsType.Bowmaster, JobsType.Marksman],
  },
  [JobsType.Magician]: {
    firstJob: JobsType.Magician,
    secondJobs: [
      JobsType.FirePoisonWizard,
      JobsType.IceLightningWizard,
      JobsType.Cleric,
    ],
    thirdJobs: [
      JobsType.FirePoisonMage,
      JobsType.IceLightningMage,
      JobsType.Priest,
    ],
    fourthJobs: [
      JobsType.FirePoisonArchMage,
      JobsType.IceLightningArchMage,
      JobsType.Bishop,
    ],
  },
  // [JobsType.Pirate]: {
  //   firstJob: JobsType.Rogue,
  //   secondJobs: [JobsType.Brawler, JobsType.Gunslinger],
  //   thirdJobs: [JobsType.Marauder, JobsType.Outlaw],
  //   fourthJobs: [JobsType.Buccaneer, JobsType.Corsair],
  // },
  [JobsType.Thief]: {
    firstJob: JobsType.Thief,
    secondJobs: [JobsType.Assassin, JobsType.Bandit],
    thirdJobs: [JobsType.Hermit, JobsType.ChiefBandit],
    fourthJobs: [JobsType.NightLord, JobsType.Shadower],
  },
  // [JobsType.Warrior]: {
  //   firstJob: JobsType.Swordman,
  //   secondJobs: [JobsType.Fighter, JobsType.Page, JobsType.Spearman],
  //   thirdJobs: [JobsType.Crusader, JobsType.WhiteKnight, JobsType.DragonKnight],
  //   fourthJobs: [JobsType.Hero, JobsType.Paladin, JobsType.DarkKnight],
  // },
};
